# Generated by Django 5.2.7 on 2025-12-05 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_rename_fecha_creado_proyecto_creado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='creado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='proyectos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
