# Generated by Django 5.2.7 on 2025-11-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo_favorito', models.CharField(choices=[('moderno', 'Moderno'), ('minimalista', 'Minimalista'), ('rustico', 'Rústico'), ('clasico', 'Clásico')], max_length=50)),
                ('colores_preferidos', models.CharField(max_length=200)),
                ('presupuesto', models.IntegerField()),
                ('ambientes_interes', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
