# Generated by Django 5.2.7 on 2026-07-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas', '0004_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_cliente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mensaje', models.TextField(blank=True)),
                ('respuesta_proveedor', models.TextField(blank=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada_proveedor', 'Aceptada por el proveedor'), ('confirmada', 'Confirmada por el cliente'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicio', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='herramientas.proyecto')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
