# Generated by Django 5.2.7 on 2025-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_creado',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('living', 'Living'), ('cocina', 'Cocina'), ('banio', 'Baño'), ('dormitorio', 'Dormitorio'), ('oficina', 'Oficina'), ('exterior', 'Exterior')], default='living', max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
